name: Conecta-Repo
on: 
  push:
    branches:
      - main
jobs:
  Integra-Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Action de integração dos repositórios
        uses: peter-evans/repository-dispatch@v3
        with: 
          token: $${{secrets.QA_REPO_TOKEN}}   

          repository: IgorFelixSqa/Projeto-login-Testes

          event-type: IntegraRepositorios
